### ISSUE TITLE
Compilation Error for adventure.c

### ISSUE THREAD

**Issue by CaptainDaVinci** [k-cal/C-Projects#1]
On compiling the code in GCC compiler, Linux environment, compilation error occurs.

```
$ gcc adventure.c
warning: implicit declaration of function ‘mkdir’ [-Wimplicit-function-declaration]
   mkdir(directory, 0755);
```

**Comment by k-cal** [comment]
Sorry about that. I added back in the proper headers and at the very least mkdir should work now.
